//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from p4.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Ip4Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class p4BaseListener : Ip4Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterS([NotNull] p4Parser.SContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitS([NotNull] p4Parser.SContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] p4Parser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] p4Parser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] p4Parser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] p4Parser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] p4Parser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] p4Parser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.returnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnExpr([NotNull] p4Parser.ReturnExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.returnExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnExpr([NotNull] p4Parser.ReturnExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDcl([NotNull] p4Parser.FuncDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDcl([NotNull] p4Parser.FuncDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] p4Parser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] p4Parser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] p4Parser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] p4Parser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.returnsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnsStmt([NotNull] p4Parser.ReturnsStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.returnsStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnsStmt([NotNull] p4Parser.ReturnsStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] p4Parser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] p4Parser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] p4Parser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] p4Parser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctioncall([NotNull] p4Parser.FunctioncallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctioncall([NotNull] p4Parser.FunctioncallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] p4Parser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] p4Parser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlStructure([NotNull] p4Parser.ControlStructureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlStructure([NotNull] p4Parser.ControlStructureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] p4Parser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] p4Parser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStmt([NotNull] p4Parser.ElseStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStmt([NotNull] p4Parser.ElseStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.loopStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStructure([NotNull] p4Parser.LoopStructureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.loopStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStructure([NotNull] p4Parser.LoopStructureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.forexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForexpr([NotNull] p4Parser.ForexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.forexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForexpr([NotNull] p4Parser.ForexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.whileexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileexpr([NotNull] p4Parser.WhileexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.whileexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileexpr([NotNull] p4Parser.WhileexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.foreachexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachexpr([NotNull] p4Parser.ForeachexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.foreachexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachexpr([NotNull] p4Parser.ForeachexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStmt([NotNull] p4Parser.SwitchStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStmt([NotNull] p4Parser.SwitchStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBody([NotNull] p4Parser.SwitchBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBody([NotNull] p4Parser.SwitchBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchItem([NotNull] p4Parser.SwitchItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchItem([NotNull] p4Parser.SwitchItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] p4Parser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] p4Parser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.condExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondExpr([NotNull] p4Parser.CondExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.condExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondExpr([NotNull] p4Parser.CondExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.logORexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogORexpr([NotNull] p4Parser.LogORexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.logORexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogORexpr([NotNull] p4Parser.LogORexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.logANDexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogANDexpr([NotNull] p4Parser.LogANDexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.logANDexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogANDexpr([NotNull] p4Parser.LogANDexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] p4Parser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] p4Parser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelExpr([NotNull] p4Parser.RelExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelExpr([NotNull] p4Parser.RelExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] p4Parser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] p4Parser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.multExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultExpr([NotNull] p4Parser.MultExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.multExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultExpr([NotNull] p4Parser.MultExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] p4Parser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] p4Parser.ExprListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.postExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostExpr([NotNull] p4Parser.PostExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.postExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostExpr([NotNull] p4Parser.PostExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.primExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimExpr([NotNull] p4Parser.PrimExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.primExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimExpr([NotNull] p4Parser.PrimExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] p4Parser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] p4Parser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix([NotNull] p4Parser.PostfixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.postfix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix([NotNull] p4Parser.PostfixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefix([NotNull] p4Parser.PrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefix([NotNull] p4Parser.PrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.valuetype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValuetype([NotNull] p4Parser.ValuetypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.valuetype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValuetype([NotNull] p4Parser.ValuetypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.returntype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturntype([NotNull] p4Parser.ReturntypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.returntype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturntype([NotNull] p4Parser.ReturntypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] p4Parser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] p4Parser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] p4Parser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] p4Parser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.assnOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssnOp([NotNull] p4Parser.AssnOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.assnOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssnOp([NotNull] p4Parser.AssnOpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
