//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from p4.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Ip4Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class p4BaseListener : Ip4Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterS([NotNull] p4Parser.SContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.s"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitS([NotNull] p4Parser.SContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStmt([NotNull] p4Parser.ImportStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStmt([NotNull] p4Parser.ImportStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.initStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitStmt([NotNull] p4Parser.InitStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.initStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitStmt([NotNull] p4Parser.InitStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDcl([NotNull] p4Parser.VarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDcl([NotNull] p4Parser.VarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] p4Parser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] p4Parser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] p4Parser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] p4Parser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDcl([NotNull] p4Parser.FuncDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDcl([NotNull] p4Parser.FuncDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] p4Parser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] p4Parser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] p4Parser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] p4Parser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] p4Parser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] p4Parser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] p4Parser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] p4Parser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlStructure([NotNull] p4Parser.ControlStructureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlStructure([NotNull] p4Parser.ControlStructureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] p4Parser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] p4Parser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStmt([NotNull] p4Parser.ElseStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStmt([NotNull] p4Parser.ElseStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.forExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForExpr([NotNull] p4Parser.ForExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.forExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForExpr([NotNull] p4Parser.ForExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.whileExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileExpr([NotNull] p4Parser.WhileExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.whileExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileExpr([NotNull] p4Parser.WhileExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.foreachExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachExpr([NotNull] p4Parser.ForeachExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.foreachExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachExpr([NotNull] p4Parser.ForeachExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStmt([NotNull] p4Parser.SwitchStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStmt([NotNull] p4Parser.SwitchStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBody([NotNull] p4Parser.SwitchBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBody([NotNull] p4Parser.SwitchBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchItem([NotNull] p4Parser.SwitchItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchItem([NotNull] p4Parser.SwitchItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] p4Parser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] p4Parser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelExpr([NotNull] p4Parser.RelExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelExpr([NotNull] p4Parser.RelExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExpr([NotNull] p4Parser.BoolExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExpr([NotNull] p4Parser.BoolExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] p4Parser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] p4Parser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.boolTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolTerm([NotNull] p4Parser.BoolTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.boolTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolTerm([NotNull] p4Parser.BoolTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathExpr([NotNull] p4Parser.MathExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mathExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathExpr([NotNull] p4Parser.MathExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpr([NotNull] p4Parser.MulExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpr([NotNull] p4Parser.MulExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mathTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathTerm([NotNull] p4Parser.MathTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mathTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathTerm([NotNull] p4Parser.MathTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVal([NotNull] p4Parser.ValContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.val"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVal([NotNull] p4Parser.ValContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.indexVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexVal([NotNull] p4Parser.IndexValContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.indexVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexVal([NotNull] p4Parser.IndexValContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] p4Parser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] p4Parser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctioncall([NotNull] p4Parser.FunctioncallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctioncall([NotNull] p4Parser.FunctioncallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] p4Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] p4Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] p4Parser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] p4Parser.ReturnStmtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
