//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from p4.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="p4Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface Ip4Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] p4Parser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] p4Parser.SContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] p4Parser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] p4Parser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.initStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitStmt([NotNull] p4Parser.InitStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.initStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitStmt([NotNull] p4Parser.InitStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([NotNull] p4Parser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([NotNull] p4Parser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] p4Parser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] p4Parser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] p4Parser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] p4Parser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDcl([NotNull] p4Parser.FuncDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDcl([NotNull] p4Parser.FuncDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParams([NotNull] p4Parser.ParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParams([NotNull] p4Parser.ParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] p4Parser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] p4Parser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] p4Parser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] p4Parser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] p4Parser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] p4Parser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStructure([NotNull] p4Parser.ControlStructureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.controlStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStructure([NotNull] p4Parser.ControlStructureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] p4Parser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] p4Parser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStmt([NotNull] p4Parser.ElseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.elseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStmt([NotNull] p4Parser.ElseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.forExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForExpr([NotNull] p4Parser.ForExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.forExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForExpr([NotNull] p4Parser.ForExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.whileExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileExpr([NotNull] p4Parser.WhileExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.whileExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileExpr([NotNull] p4Parser.WhileExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.foreachExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachExpr([NotNull] p4Parser.ForeachExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.foreachExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachExpr([NotNull] p4Parser.ForeachExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStmt([NotNull] p4Parser.SwitchStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStmt([NotNull] p4Parser.SwitchStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBody([NotNull] p4Parser.SwitchBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBody([NotNull] p4Parser.SwitchBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchItem([NotNull] p4Parser.SwitchItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.switchItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchItem([NotNull] p4Parser.SwitchItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] p4Parser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] p4Parser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelExpr([NotNull] p4Parser.RelExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelExpr([NotNull] p4Parser.RelExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpr([NotNull] p4Parser.BoolExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpr([NotNull] p4Parser.BoolExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] p4Parser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] p4Parser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.boolTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolTerm([NotNull] p4Parser.BoolTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.boolTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolTerm([NotNull] p4Parser.BoolTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathExpr([NotNull] p4Parser.MathExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mathExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathExpr([NotNull] p4Parser.MathExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] p4Parser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] p4Parser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.mathTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathTerm([NotNull] p4Parser.MathTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.mathTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathTerm([NotNull] p4Parser.MathTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVal([NotNull] p4Parser.ValContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.val"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVal([NotNull] p4Parser.ValContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.indexVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexVal([NotNull] p4Parser.IndexValContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.indexVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexVal([NotNull] p4Parser.IndexValContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] p4Parser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] p4Parser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] p4Parser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] p4Parser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] p4Parser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] p4Parser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="p4Parser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] p4Parser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="p4Parser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] p4Parser.ReturnStmtContext context);
}
